sonata_block:
  blocks:
    # enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts: [admin]

sonata_admin:
  title: Battery Chain
  title_logo: resources/batterychain_logo.png
  templates:
    layout: 'layout.html.twig'
  options:
    html5_validate: true
  dashboard:
    groups:
      User:
        icon: '<i class="fa fa-users"></i>'
        on-top: true
        roles: ['ROLE_SUPER_ADMIN']
      Manufacturer:
        icon: '<i class="fa fa-industry"></i>'
        on-top: true
        roles: ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN']
      "Pickup Partner and Recycler":
        icon: '<i class="fa fa-recycle"></i>'
        on-top: true
        roles: ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN', 'ROLE_MANUFACTURER']
      Battery:
        icon: '<i class="fa fa-battery"></i>'
        on-top: true
        roles: [ 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN', 'ROLE_MANUFACTURER' ]
      "Return/Recycle":
        icon: '<i class="fa fa-recycle"></i>'
        on-top: true
        roles: [ 'ROLE_MANUFACTURER' ]
      Delivery:
        icon: '<i class="fa fa-truck"></i>'
        on-top: true
        roles: [ 'ROLE_MANUFACTURER' ]
      Import:
        icon: '<i class="fa fa-file-csv"></i>'
        on-top: true
        roles: [ 'ROLE_MANUFACTURER' ]
      ModifiedBattery:
        icon: '<i class="fa fa-gears"></i>'
        on-top: true
        roles: [ 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN', 'ROLE_MANUFACTURER' ]