sonata_block:
  blocks:
    # enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts: [admin]

sonata_admin:
  title: Battery Chain
  title_logo: resources/logo.ico
  templates:
    layout: 'layout.html.twig'
  options:
    html5_validate: true
  dashboard:
    groups:
      Manufacturer:
        icon: '<i class="fa fa-industry"></i>'
        on-top: true
        roles: ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN']
      Recycler:
        icon: '<i class="fa fa-recycle"></i>'
        on-top: true
        roles: ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN', 'ROLE_MANUFACTURER']
      Battery:
        icon: '<i class="fa fa-battery"></i>'
        on-top: true
        roles: [ 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN', 'ROLE_MANUFACTURER' ]
      Return:
        icon: '<i class="fa fa-file"></i>'
        on-top: true
        roles: [ 'ROLE_MANUFACTURER' ]
      Delivery:
        icon: '<i class="fa fa-file"></i>'
        on-top: true
        roles: [ 'ROLE_MANUFACTURER' ]