twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        support_email: '%env(SUPPORT_EMAIL_ADDRESS)%'
        live_url: '%env(LIVE_URL)%'
        defaultLocale: '%env(DEFAULT_LOCALE)%'
        locales: '%env(APP_LOCALES)%'
        etherscan_url: '%env(ETHERSCAN_URL)%'
        logo_path: '%app.path.manufacturer_logos%'
        co2_path: '%app.path.co2_icons%'
        insurance_path: '%app.path.insurance_icons%'
        no_image_path: '%app.path.no_image%'
        logo_aws_path: '%app.path.manufacturer_aws_logos%'
        co2_aws_path: '%app.path.co2_aws_icons%'
        insurance_aws_path: '%app.path.insurance_aws_icons%'
when@test:
    twig:
        strict_variables: true
