twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        support_email: '%env(SUPPORT_EMAIL_ADDRESS)%'
when@test:
    twig:
        strict_variables: true
