index:
    path: /
    controller: App\Controller\DefaultController::index
app_logout:
    path: /logout
    methods: GET
app_register:
    path: /register
    controller: App\Controller\UserController::index