services:
  bc.aws_s3.client:
    class: Aws\S3\S3Client
    factory: [Aws\S3\S3Client, 'factory']
    arguments:
      -
        version: 'latest'
        region: '%env(AWS_REGION)%'
        credentials:
          key: '%env(AWS_KEY)%'
          secret: '%env(AWS_SECRET)%'