# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $csvFileUploadSize: '%env(CSV_FILE_UPLOAD_SIZE)%'
            $recaptchaSecretKey: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
            $kernelProjectDir: '%kernel.project_dir%'
            $mailjetKey: '%env(MAILJET_KEY)%'
            $mailjetSecret: '%env(MAILJET_SECRET)%'
            $mailjetFromName: '%env(MAILJET_FROM_NAME)%'
            $mailjetFromEmail: '%env(MAILJET_FROM_EMAIL)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        calls:
            - [ setRoles, [ "%security.role_hierarchy.roles%" ] ]
            - [ setPasswordEncoder, [ '@security.password_hasher' ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User, show_in_dashboard: false }

    admin.manufacturer:
        class: App\Admin\ManufacturerAdmin
        arguments: [~, App\Entity\Manufacturer, ~]
        calls:
            - [ setPasswordEncoder, [ '@security.password_hasher' ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Manufacturer, group: Manufacturer }

    admin.recycler:
        class: App\Admin\RecyclerAdmin
        arguments: [~, App\Entity\Recycler, App\Controller\RecyclerController]
        calls:
            - [ setPasswordEncoder, [ '@security.password_hasher' ] ]
            - [ setTokenStorage, [ '@security.token_storage' ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Recycler, group: Recycler }

    admin.battery:
        class: App\Admin\BatteryAdmin
        arguments: [~, App\Entity\Battery, App\Controller\BatteryController]
        calls:
            - [ setTokenStorage, [ '@security.token_storage' ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Battery, group: Battery }

    admin.return:
        class: App\Admin\BatteryReturnAdmin
        arguments: [~, App\Entity\BatteryReturn, App\Controller\ReturnController]
        calls:
            - [ setTokenStorage, [ '@security.token_storage' ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Returns, group: Return }

    admin.country:
        class: App\Admin\CountryAdmin
        arguments: [~, App\Entity\Country, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Country, group: Country }

    admin.battery.type:
        class: App\Admin\BatteryTypeAdmin
        arguments: [~, App\Entity\BatteryType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: BatteryType, group: BatteryType }

    admin.shipment:
        class: App\Admin\ShipmentAdmin
        arguments: [~, App\Entity\Shipment, App\Controller\ShipmentController]
        calls:
            - [ setTokenStorage, [ '@security.token_storage' ] ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Delivery, group: Delivery }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]