<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class AvailableRecyclerFormType
 * @package App\Form
 */
class AvailableRecyclerFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        if (!empty($options['manufacturers'])) {
            $builder->add(
                'manufacturers',
                ChoiceType::class,
                [
                    'required' => true,
                    'label' => 'Manufacturer',
                    'choices' => $options['manufacturers']
                ]
            );
        }

        $builder->add('country', ChoiceType::class, [
            'multiple' => false,
            'choices' => $options['countries']
        ]);
        $builder
            ->add('recycler', ChoiceType::class, [
                'multiple' => true,
                'choices' => $options['recyclers']
            ])
            ->add(
            'attach',
            SubmitType::class,
            ['label' => 'Add Recycler', 'attr' => ['class' => 'btn btn-primary', 'style'=> 'margin-top:10px;']]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            'countries' => null,
            'recyclers' => null,
            'manufacturers' => null
        ]);
    }
}