<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class BatteryDetailFormType
 * @package App\Form
 */
class BatteryDetailFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('battery', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Insert Serial Number'
                ],
                'label' => false,
                'required' => true,
            ])
            ->add('search', SubmitType::class, [
                'attr' => [
                    'class' => 'search-btn btn btn-primary',
                ],
                'label' => 'Search'
            ]);

    }
}