<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class BatteryDetailFormType
 * @package App\Form
 */
class BatteryDetailFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('battery', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Enter Serial Number'
                ],
                'label' => false,
                'required' => true,
                'help' => '<i class="fa fa-info-circle mr-1"></i>You can find the Serial Number or ID on the label of your battery',
                'help_html' => true,
                'help_attr' => [
                    'class' => 'mt-2'
                ]
            ])
            ->add('search', SubmitType::class, [
                'attr' => [
                    'class' => 'search-btn btn btn-primary',
                    'style' => "background-color: #55bc5e; border-color: #55bc5e"
                ],
                'label' => 'Search'
            ]);

    }
}