<?php

namespace App\Form;

use App\Entity\Battery;
use App\Entity\Import;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Vich\UploaderBundle\Form\Type\VichFileType;

/**
 * Class BulkImportBatteryFormType
 * @package App\Form
 */
class BulkImportBatteryFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        if (!empty($options['manufacturer'])) {
            $builder->add(
                'manufacturer',
                ChoiceType::class,
                [
                    'required' => true,
                    'label' => 'Manufacturer',
                    'choices' => $options['manufacturer']
                ]
            );
        }

        $builder
            ->add('csvFile', VichFileType::class, array(
                'required'      => true,
                'allow_delete'  => false,
                'download_link' => false,
                'label' => 'Bulk Csv',
                'label_attr' => [
                    'style' => 'margin-top:10px',
                    'display' => 'inline-block !important'
                ],
                'attr' => [
                    'class' => 'inline-block',
                    'style' => 'margin-top:10px',
                    'display' => 'inline-block !important'
                ],
                'constraints' => [
                    new File([
                        'maxSize' => '5M',
                        'mimeTypes' => [
                            'text/plain',
                            'text/csv',
                            'text/x-csv'
                        ]
                    ])
                ])
            );
        $builder->add(
            'save',
            SubmitType::class,
            ['label' => 'Bulk Import', 'attr' => ['class' => 'btn btn-green', 'style'=> 'margin-top:10px;']]
        );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Import::class,
            'manufacturer' => null,
        ]);
    }
}