<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class BulkImportBatteryFormType
 * @package App\Form
 */
class BulkImportBatteryFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder->add('csv', FileType::class, ['required' => true, 'label' => 'CSV']);
        $builder->add(
            'save',
            SubmitType::class,
            ['label' => 'Bulk Import', 'attr' => ['class' => 'btn btn-primary', 'style'=> 'margin-top:10px;']]
        );
    }
}