<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class BulkUpdateRecyclerFormType
 * @package App\Form
 */
class BulkUpdateRecyclerFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('region', ChoiceType::class, [
                'multiple' => false,
                'label' => 'Country',
                'choices' => $options['regions']
            ])
            ->add('csv', FileType::class, ['required' => true, 'label' => 'CSV']);
        $builder->add(
            'save',
            SubmitType::class,
            ['label' => 'Bulk Update/Insert', 'attr' => ['class' => 'btn btn-primary', 'style'=> 'margin-top:10px;']]
        );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'manufacturer' => null,
            'regions' => null,
        ]);
    }
}