<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ReportBatteryReturnFormType
 * @package App\Form
 */
class ReportBatteryReturnFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('recyclers', ChoiceType::class, [
                'multiple' => false,
                'required' => true,
                'choices' => array_merge([
                    'Select Recycler' => ""
                ], $options['recyclers']),
                'attr' => [
                    'class' => 'form-select'
                ],
                'label_attr' => [
                    'class' => 'fw-bold'
                ],
            ])
            ->add(
                'submit',
                SubmitType::class,
                ['label' => 'Report Battery Return', 'attr' => ['class' => 'btn btn-primary mr-5', 'style'=> 'margin-top:10px;']]
            )
            ->add(
                'cancel',
                SubmitType::class,
                [
                    'label' => 'Cancel',
                    'attr' => [
                        'class' => 'btn btn-light',
                        'style'=> 'margin-top:10px;',
                        'formnovalidate'=>'formnovalidate'
                    ]
                ]
            );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'recyclers' => []
        ]);
    }
}