<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ReturnFormType
 * @package App\Form
 */
class ReturnFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('battery', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Insert Serial Number'
                ],
                'required' => true,
            ]);
            if (!empty($options['manufacturer'])) {
                $builder->add(
                    'manufacturer',
                    ChoiceType::class,
                    [
                        'required' => $options['is_admin'],
                        'label' => 'Battery\'s Manufacturer',
                        'choices' => $options['manufacturer']
                    ]
                );
            }
            $builder->add('recycler', ChoiceType::class, [
                'choices' => $options['recyclers'],
                'required' => true,
            ]);
        $builder
            ->add(
            $builder->create('information', FormType::class, ['by_reference' => false,
                'label_attr' => ['style' => 'font-size: medium'], 'required' => false, 'label' => 'Additional Information (optional)',
            ])
                ->add('address', TextType::class, [
                    'attr' => [
                        'class' => 'form-control'
                    ],
                    'required' => false,
                ])
                ->add('postalCode', TextType::class, [
                    'attr' => [
                        'class' => 'form-control'
                    ],
                    'label' => 'Post Code',
                    'required' => false,
                ])
                ->add('city', TextType::class, [
                    'attr' => [
                        'class' => 'form-control'
                    ],
                    'required' => false,
                ])
                ->add('country', TextType::class, [
                    'attr' => [
                        'class' => 'form-control'
                    ],
                    'required' => false,
                ])
        );

        $builder->add(
            'submit',
            SubmitType::class,
            ['label' => 'Add Return', 'attr' => ['class' => 'btn btn-green', 'style'=> 'margin-top:10px;']]
        )
        ->add('cancel',
            SubmitType::class,
            [
                'label' => 'Cancel',
                'attr' => [
                    'class' => 'btn btn-outline-green',
                    'style'=> 'margin-top:10px;',
                    'formnovalidate'=>'formnovalidate'
                ]
            ]
        );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'csrf_protection' => false,
            'recyclers' => null,
            'manufacturer' => null,
            'is_admin' => false
        ]);
    }
}