<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;

/**
 * Class ReturnPublicFormType
 * @package App\Form
 */
class ReturnPublicFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('country', ChoiceType::class, [
                'multiple' => false,
                'required' => true,
                'choices' => array_merge([
                    'Select Country' => ''
                ], $options['countries']),
                'attr' => [
                    'class' => 'form-select',
                    'size' => 1
                ],
                'label_attr' => [
                    'class' => 'fw-bold mb-1 mt-1'
                ],
                'data' => $options['default_country']
            ]);

        if (empty($options['recyclers'])) {
            $builder
                ->add('recyclers', ChoiceType::class, [
                    'multiple' => false,
                    'required' => true,
                    'choices' => [
                        'No Pickup Partner Found' => ""
                    ],
                    'attr' => [
                        'class' => 'form-select'
                    ],
                    'label_attr' => [
                        'class' => 'fw-bold mb-1 mt-1'
                    ],
                    'label' => 'Select Pickup Service or Recycler'
                ]);
        } else {
            $builder
                ->add('recyclers', ChoiceType::class, [
                    'multiple' => false,
                    'required' => true,
                    'choices' => $options['recyclers'],
                    'attr' => [
                        'class' => 'form-select'
                    ],
                    'label_attr' => [
                        'class' => 'fw-bold mb-1 mt-1'
                    ],
                    'label' => 'Select Pickup Service or Recycler'
                ]);
        }

        $builder
            ->add('recyclerId', HiddenType::class, [])
            ->add('fallback', HiddenType::class, [
                'data' => $options['fall_back']
            ])
            ->add('dataPolicy', CheckboxType::class, [
                'attr' => [
                    'class' => 'mt-3'
                ],
                'required' => false,
                'label'    => 'Accept the data privacy policy.',
                'label_attr' => [
                    'class' => 'fw-bold mb-1 mt-1'
                ],
                'mapped' => false,
                'constraints' => [
                    new IsTrue([
                        'message' => 'You must agree to our terms.'
                    ])
                ]
            ]);

        $builder
            ->add(
                $builder->create('information', FormType::class, [
                    'by_reference' => false,
                    'label_attr' => ['style' => 'font-size: medium', 'class' => 'fw-bold'],
                    'required' => false, 'label' => 'Contact Information (Who to contact for the pickup service)',
                ])
                    ->add('name', TextType::class, [
                        'attr' => [
                            'class' => 'form-control'
                        ],
                        'required' => false,
                        'label_attr' => [
                            'class' => 'fw-bold mb-1 mt-1'
                        ]
                    ])
                    ->add('email', TextType::class, [
                        'attr' => [
                            'class' => 'form-control'
                        ],
                        'required' => false,
                        'label_attr' => [
                            'class' => 'fw-bold mb-1 mt-1'
                        ]
                    ])
                    ->add('contact', TextType::class, [
                        'attr' => [
                            'class' => 'form-control'
                        ],
                        'label' => "Phone Number (optional)",
                        'required' => false,
                        'label_attr' => [
                            'class' => 'fw-bold mb-1 mt-1'
                        ]
                    ])
            );

        $builder->add(
            'submit',
            SubmitType::class,
            [
                'label' => 'Contact Partner',
                'attr' => [
                    'class' => 'btn btn-green mr-5',
                    'style' => 'margin-top:10px;',
                    'disabled' => 'disabled'
                ]
            ]
        )
            ->add('cancel',
                SubmitType::class,
                [
                    'label' => 'Cancel',
                    'attr' => [
                        'class' => 'btn btn-light btn-outline-green',
                        'style'=> 'margin-top:10px;',
                        'formnovalidate'=>'formnovalidate'
                    ]
                ]
            );
    }


    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'recyclers' => [],
            'countries' => [],
            'default_country' => 1,
            'fall_back' => false
        ]);
    }
}