<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ShipmentFormType
 * @package App\Form
 */
class ShipmentFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('battery', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Insert Serial Number'
                ],
                'required' => true,
            ]);
        $builder->add(
            $builder->create('information', FormType::class, ['by_reference' => false,
                'label_attr' => ['style' => 'font-size: medium'], 'required' => false, 'label' => 'Additional Information (optional)',
            ])
                ->add('address', TextType::class, [
                    'attr' => [
                        'class' => 'form-control'
                    ],
                    'required' => false,
                ])
                ->add('city', TextType::class, [
                    'attr' => [
                        'class' => 'form-control'
                    ],
                    'required' => false,
                ])
                ->add('country', TextType::class, [
                    'attr' => [
                        'class' => 'form-control'
                    ],
                    'required' => false,
                ])
        );

        $builder->add(
            'submit',
            SubmitType::class,
            ['label' => 'Add Delivery', 'attr' => ['class' => 'btn btn-primary', 'style'=> 'margin-top:10px;']]
        )
        ->add('cancel',
            SubmitType::class,
            [
                'label' => 'Cancel',
                'attr' => [
                    'class' => 'btn btn-default',
                    'style'=> 'margin-top:10px;',
                    'formnovalidate'=>'formnovalidate'
                ]
            ]
        );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'batteries' => null,
            'csrf_protection' => false,
        ]);
    }
}