<?php

namespace App\Form;

use App\Entity\Battery;
use App\Entity\Distributor;
use App\Entity\Recycler;
use Sonata\AdminBundle\Form\Type\ChoiceFieldMaskType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ShipmentFormType
 * @package App\Form
 */
class ShipmentFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('battery', EntityType::class, [
                'class' => Battery::class,
                'multiple' => true,
                'required' => true,
                'choices' => $options['batteries'],
            ]);
        $builder
            ->add('linkType', ChoiceFieldMaskType::class, [
                'choices' => [
                    'Recyclers' => 'recyclers',
                    'Distributors' => 'distributors',
                ],
                'map' => [
                    'recyclers' => ['recyclers'],
                    'distributors' => ['distributors'],
                ],
                'placeholder' => 'Choose an option',
                'required' => true,
                'label' => "Choose an option"
            ])
            ->add('recyclers', EntityType::class, [
                'class' => Recycler::class,
                'choices' => $options['recyclers'],
            ])
            ->add('distributors', EntityType::class, [
                'class' => Distributor::class,
                'choices' => $options['distributors'],
            ]);
        $builder
            ->add('address', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('city', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('country', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('status', ChoiceType::class, [
                'choices' => [
                    'Registered' => 'registered',
                    'Block Chain Secured' => 'blockchain-secured',
                    'Shipped' => 'shipped',
                    'Returned' => 'returned',
                ],
            ]);
        $builder->add(
            'submit',
            SubmitType::class,
            ['label' => 'Add Shipment', 'attr' => ['class' => 'btn btn-primary', 'style'=> 'margin-top:10px;']]
        );
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'recyclers' => null,
            'distributors' => null,
            'batteries' => null,
            'csrf_protection' => false,
        ]);
    }
}