<?php

namespace App\Admin;

use App\Entity\Manufacturer;
use App\Entity\Recycler;
use App\Entity\User;
use App\Enum\RoleEnum;
use App\Helper\CustomHelper;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\ModelType;
use Sonata\AdminBundle\Route\RouteCollectionInterface;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Component\Form\Extension\Core\Type\TextType;

/**
 * Class BatteryReturnAdmin
 * @package App\Admin
 * @property $tokenStorage
 */
class BatteryReturnAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $form): void
    {
        parent::configureFormFields($form); // TODO: Change the autogenerated stub

        $user = $this->tokenStorage->getToken()->getUser();

        if (in_array(RoleEnum::ROLE_SUPER_ADMIN, $user->getRoles(), true)) {
            $form
                ->add('recycler', ModelType::class, [
                    'class' => Recycler::class,
                    'property' => 'name',
                    'btn_add' => false,
                    'mapped' => false
                ]);
        }

        $form
            ->add('battery', ModelType::class, [
                'property' => 'serialNumber',
                'btn_add' => false
            ])
            ->add('address', TextType::class)
            ->add('city', TextType::class)
            ->add('country', TextType::class);
    }

    /**
     * @param ListMapper $list
     */
    protected function configureListFields(ListMapper $list): void
    {
        parent::configureListFields($list); // TODO: Change the autogenerated
        $list
            ->addIdentifier('battery.serialNumber')
            ->addIdentifier('address')
            ->addIdentifier('city')
            ->addIdentifier('country');
    }

    /**
     * @param DatagridMapper $filter
     */
    protected function configureDatagridFilters(DatagridMapper $filter): void
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter->add('battery.serialNumber');
    }

    /**
     * @param ShowMapper $show
     */
    protected function configureShowFields(ShowMapper $show): void
    {
        parent::configureShowFields($show); // TODO: Change the autogenerated stub
        $show
            ->add('battery.serialNumber')
            ->add('address')
            ->add('city')
            ->add('country');
    }

    /**
     * @param $tokenStorage
     */
    public function setTokenStorage($tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }

    /**
     * @param object $object
     */
    protected function prePersist(object $object): void
    {
        parent::prePersist($object); // TODO: Change the autogenerated stub

        $object->setUpdated(new \DateTime('now'));
        $user = $this->tokenStorage->getToken()->getUser();

        if ($object->getCreated() === null) {
            $object->setCreated(new \DateTime('now'));
        }

        if ($object->getReturnDate() === null) {
            $object->setReturnDate(new \DateTime('now'));
        }

        if (!in_array(RoleEnum::ROLE_SUPER_ADMIN, $user->getRoles(), true)
            && in_array(RoleEnum::ROLE_RECYCLER, $user->getRoles(), true)) {
            $object->setReturnTo($user);
        }

        if (in_array(RoleEnum::ROLE_SUPER_ADMIN, $user->getRoles(), true)) {
            $recycler = $this->getForm()->get('recycler')->getData();
            $object->setReturnTo($recycler->getUser());
        }

        $object->setReturnFrom($object->getBattery()->getCurrentPossessor());
        $object->getBattery()->setStatus(CustomHelper::BATTERY_STATUS_RETURNED);
        $object->getBattery()->setCurrentPossessor($user);
    }

    protected function preValidate(object $object): void
    {
        parent::preValidate($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $actions
     * @return array
     */
    protected function configureBatchActions(array $actions): array
    {
        unset($actions['delete']);
        return parent::configureBatchActions($actions); // TODO: Change the autogenerated stub
    }

    /**
     * @param RouteCollectionInterface $collection
     */
    protected function configureRoutes(RouteCollectionInterface $collection): void
    {
        $collection
            ->remove('create')
            ->remove('delete')
            ->remove('edit')
            ->add('return')
            ->add('bulkReturn');
    }

    /**
     * @param array $actions
     * @return array
     */
    protected function configureDashboardActions(array $actions): array
    {
        $user = $this->tokenStorage->getToken()->getUser();

        if (!in_array(RoleEnum::ROLE_SUPER_ADMIN, $user->getRoles(), true)
            && in_array(RoleEnum::ROLE_MANUFACTURER, $user->getRoles(), true)) {
            $actions['return'] = [
                'label' => 'Add Return',
                'translation_domain' => 'SonataAdminBundle',
                'url' => $this->generateUrl('return'),
                'icon' => 'fa fa-plus',
            ];
            $actions['bulkReturn'] = [
                'label' => 'Add Bulk Return',
                'translation_domain' => 'SonataAdminBundle',
                'url' => $this->generateUrl('bulkReturn'),
                'icon' => 'fa fa-file',
            ];
        }

        return $actions;
    }
}