<?php

namespace App\Admin;

use Doctrine\DBAL\Types\TextType;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;

/**
 * Class CountryAdmin
 * @package App\Admin
 */
class CountryAdmin extends AbstractAdmin
{
//    protected function configureFormFields(FormMapper $form): void
//    {
//        parent::configureFormFields($form); // TODO: Change the autogenerated stub
//        $form
//            ->add('name', TextType::class);
//    }

    protected function configureDatagridFilters(DatagridMapper $filter): void
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter
            ->add('name');
    }
}