<?php

namespace App\Admin;

use App\Entity\Manufacturer;
use App\Enum\RoleEnum;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\AdminType;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

/**
 * Class ManufacturerAdmin
 * @package App\Admin
 * @property $passwordEncoder
 */
class ManufacturerAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $form): void
    {
        parent::configureFormFields($form); // TODO: Change the autogenerated stub
        /** @var Manufacturer $manufacturer */
        $manufacturer = $this->getSubject();
        $form
            ->add('name', TextType::class);

        if ($manufacturer->getId() === null) {
            $form
                ->add('user', AdminType::class);
        } else {
            $form
                ->add('address', TextType::class)
                ->add('country', TextType::class)
                ->add('city', TextType::class)
                ->add('contact', TextType::class);
        }
    }

    /**
     * @param ListMapper $list
     */
    protected function configureListFields(ListMapper $list): void
    {
        parent::configureListFields($list); // TODO: Change the autogenerated
        $list
            ->addIdentifier('name')
            ->addIdentifier('address')
            ->addIdentifier('city')
            ->addIdentifier('country');
    }

    /**
     * @param DatagridMapper $filter
     */
    protected function configureDatagridFilters(DatagridMapper $filter): void
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter->add('name');
    }

    protected function configureShowFields(ShowMapper $show): void
    {
        parent::configureShowFields($show); // TODO: Change the autogenerated stub
        $show
            ->add('name')
            ->add('user.email', EmailType::class, [
                'label' => 'Email'
            ])
            ->add('address')
            ->add('city')
            ->add('country')
            ->add('contact');
    }

    /**
     * @param $passwordEncoder
     */
    public function setPasswordEncoder($passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    /**
     * @param object $object
     */
    protected function prePersist(object $object): void
    {
        parent::prePersist($object); // TODO: Change the autogenerated stub

        $object->setUpdated(new \DateTime('now'));

        if ($object->getCreated() === null) {
            $object->setCreated(new \DateTime('now'));
        }

        $plainPassword = $object->getUser()->getPassword();
        $encoded = $this->passwordEncoder->hashPassword($object->getUser(), $plainPassword);

        $object->getUser()->setPassword($encoded);
        $object->getUser()->setRoles([RoleEnum::ROLE_MANUFACTURER]);
    }
}