<?php

namespace App\Admin;

use App\Entity\User;
use App\Enum\RoleEnum;
use App\Helper\CustomHelper;
use App\Service\ManufacturerService;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\ProxyQueryInterface;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

/**
 * Class UserAdmin
 * @package App\Admin
 * @property $roles
 * @property $passwordEncoder
 * @property ManufacturerService $manufacturerService
 * @property $tokenStorage
 */
class UserAdmin extends AbstractAdmin
{
    /**
     * @param $tokenStorage
     */
    public function setTokenStorage($tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }

    /**
     * @param FormMapper $form
     */
    protected function configureFormFields(FormMapper $form): void
    {
        parent::configureFormFields($form); // TODO: Change the autogenerated stub

        $rolesChoices = self::flattenRoles($this->roles);
        $form
            ->add('firstName', TextType::class)
            ->add('lastName', TextType::class)
            ->add('email', EmailType::class)
            ->add('password', PasswordType::class)
            ->add('roles', ChoiceType::class, [
                'choices' => $rolesChoices,
                'multiple' => true
            ]);
    }

    /**
     * @param ListMapper $list
     */
    protected function configureListFields(ListMapper $list): void
    {
        parent::configureListFields($list); // TODO: Change the autogenerated
        $list
            ->addIdentifier('firstName')
            ->addIdentifier('lastName')
            ->addIdentifier('email')
            ->addIdentifier('status');
    }

    /**
     * @param DatagridMapper $filter
     */
    protected function configureDatagridFilters(DatagridMapper $filter): void
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
        $filter->add('email');
    }

    /**
     * Turns the role's array keys into string <ROLES_NAME> keys.
     * @param $rolesHierarchy
     * @return array
     * @todo Move to convenience or make it recursive ? ;-)
     */
    protected static function flattenRoles($rolesHierarchy): array
    {
        $flatRoles = [];
        foreach ($rolesHierarchy as $key => $roles) {
            $flatRoles[$key] = $key;
            if (empty($roles)) {
                continue;
            }

            foreach($roles as $role) {
                if(!isset($flatRoles[$role])) {
                    $flatRoles[$role] = $role;
                }
            }
        }

        return $flatRoles;
    }

    /**
     * @param $roles
     */
    public function setRoles($roles)
    {
        $this->roles = $roles;
    }

    /**
     * @param $passwordEncoder
     */
    public function setPasswordEncoder($passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    /**
     * @param object $object
     */
    protected function prePersist(object $object): void
    {
        parent::prePersist($object); // TODO: Change the autogenerated stub

        $object->setUpdated(new \DateTime('now'));

        if ($object->getCreated() === null) {
            $object->setCreated(new \DateTime('now'));
        }

        $plainPassword = $object->getPassword();
        $encoded = $this->passwordEncoder->hashPassword($object, $plainPassword);
        $object->setPassword($encoded);
        $object->setIsVerified(CustomHelper::IS_VERIFIED);
    }

    /**
     * @param ManufacturerService $manufacturerService
     */
    public function setManufacturerService(ManufacturerService $manufacturerService)
    {
        $this->manufacturerService = $manufacturerService;
    }

    /**
     * @param object $object
     */
    protected function postPersist(object $object): void
    {
        parent::postPersist($object); // TODO: Change the autogenerated stub

        if (in_array(RoleEnum::ROLE_MANUFACTURER, $object->getRoles())) {
            /** @var User $object */
            $this->manufacturerService->createBasicManufacturer($object);
        }
    }

    /**
     * @param ShowMapper $show
     */
    protected function configureShowFields(ShowMapper $show): void
    {
        parent::configureShowFields($show); // TODO: Change the autogenerated stub
        $show
            ->add('firstname')
            ->add('lastname')
            ->add('email', EmailType::class, [
                'label' => 'Email'
            ])
            ->add('roles');
    }

    /**
     * @param object $object
     */
    protected function postRemove(object $object): void
    {
        parent::postRemove($object); // TODO: Change the autogenerated stub
        if (in_array(RoleEnum::ROLE_MANUFACTURER, $object->getRoles())) {
            /** @var User $object */
            $this->manufacturerService->removeManufacturer($object);
        }
    }

    /**
     * @param object $object
     */
    protected function preUpdate(object $object): void
    {
        parent::preUpdate($object); // TODO: Change the autogenerated stub

        $object->setUpdated(new \DateTime('now'));
        $plainPassword = $object->getPassword();
        $encoded = $this->passwordEncoder->hashPassword($object, $plainPassword);
        $object->setPassword($encoded);
    }

    /**
     * @param object $object
     */
    protected function postUpdate(object $object): void
    {
        parent::postUpdate($object); // TODO: Change the autogenerated stub

        if (in_array(RoleEnum::ROLE_MANUFACTURER, $object->getRoles())) {
            /** @var User $object */
            $this->manufacturerService->updateBasicManufacturer($object);
        }
    }

    /**
     * @param ProxyQueryInterface $query
     * @return ProxyQueryInterface
     */
    protected function configureQuery(ProxyQueryInterface $query): ProxyQueryInterface
    {
        $query = parent::configureQuery($query);
        /** @var User $user */
        $user = $this->tokenStorage->getToken()->getUser();

        if (in_array(RoleEnum::ROLE_SUPER_ADMIN, $user->getRoles(), true)) {
            $rootAlias = current($query->getRootAliases());
            $query->andWhere(
                $query->expr()->neq($rootAlias . '.id', $user->getId())
            );
        }

        return $query;
    }
}
